[package]
name = "tiff"
version = "0.5.0"
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>",
    "HeroicKatora",
    "Calum",
    "CensoredUsername <cens.username@gmail.com>",
    "Robzz",
    "birktj"]
license = "MIT"
description = "TIFF decoding and encoding library in pure Rust"
repository = "https://github.com/image-rs/image-tiff"
exclude = ["tests/images/*", "tests/fuzz_images/*"]

[dependencies]
byteorder = "1.2"
lzw = { git = "https://github.com/Rogach/lzw" }
miniz_oxide = "0.3"
